version: '3.7'

services:
    test-mysql:
        image: mysql:5.7
        container_name: test-mysql
        ports:
            - 3308:3306
        restart: always
        volumes:
            - ./docker/data/mysql:/var/lib/mysql:delegated,rw
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - test
    test-php:
        build: docker/php/
        container_name: test-php
        ports:
            - 9001:9000
        restart: always
        volumes:
            - ./:/var/www/test-task:cached
            - /etc/timezone:/etc/timezone:cached
        networks:
            - test
        depends_on:
            - test-mysql
            - test-rabbitmq
    test-nginx:
        build: docker/nginx/
        container_name: test-nginx
        ports:
            - 8085:80
        restart: always
        volumes_from:
            - test-php
        networks:
            - test
        depends_on:
            - test-php
    test-rabbitmq:
        image: rabbitmq:3-management
        container_name: test-rabbitmq
        restart: always
        hostname: rabbitmq
        volumes:
            - ./docker/data/rabbitmq/etc/:/etc/rabbitmq/:delegated,rw
            - ./docker/data/rabbitmq/data/:/var/lib/rabbitmq/:delegated,rw
            - ./docker/data/rabbitmq/logs/:/var/log/rabbitmq/:delegated,rw
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - test

networks:
    test:
        driver: bridge
